# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fast_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastPrint(object):
    def setupUi(self, FastPrint):
        FastPrint.setObjectName("FastPrint")
        FastPrint.resize(220, 161)
        self.centralwidget = QtWidgets.QWidget(FastPrint)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 80, 141, 18))
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 221, 16))
        self.label_2.setObjectName("label_2")
        FastPrint.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FastPrint)
        self.statusbar.setObjectName("statusbar")
        FastPrint.setStatusBar(self.statusbar)

        self.retranslateUi(FastPrint)
        QtCore.QMetaObject.connectSlotsByName(FastPrint)

    def retranslateUi(self, FastPrint):
        _translate = QtCore.QCoreApplication.translate
        FastPrint.setWindowTitle(_translate("FastPrint", "[AB] FastPrint (pages)"))
        self.label.setText(_translate("FastPrint", "Выбор страниц"))
        self.pushButton.setText(_translate("FastPrint", "Печать"))
        self.checkBox.setText(_translate("FastPrint", "Двусторонняя печать"))
        self.label_2.setText(_translate("FastPrint", "Файл не определен"))
